import { Banner } from "./types";
import { uid } from "./utils";

// Email Capture Template
export const emailCaptureTemplate = (): Banner => ({
    id: "bn_" + uid(),
    name: "Email Capture",
    status: "draft",
    type: "modal",
    views: {
        desktop: {
            width: 700,
            height: 450,
            background: "#ffffff",
            borderRadius: 12,
            boxShadow: "0 20px 60px rgba(0, 0, 0, 0.3)",
            layers: [
                // Yellow background section
                {
                    id: "l_" + uid(),
                    type: "shape",
                    name: "Yellow Background",
                    visible: true,
                    content: "",
                    position: { x: 0, y: 0 },
                    size: { width: 350, height: 450 },
                    style: {
                        backgroundColor: "#F5C542",
                        borderRadius: "12px 0 0 12px",
                    },
                },
                // Car image
                {
                    id: "l_" + uid(),
                    type: "image",
                    name: "Car Image",
                    visible: true,
                    content: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='200' height='150'%3E%3Crect fill='%23F5C542' width='200' height='150'/%3E%3Ctext x='50%25' y='50%25' text-anchor='middle' dy='.3em' fill='white' font-size='20'%3E🚗%3C/text%3E%3C/svg%3E",
                    position: { x: 75, y: 150 },
                    size: { width: 200, height: 150 },
                    style: {},
                },
                // Close button
                {
                    id: "l_" + uid(),
                    type: "close_button",
                    name: "Close Button",
                    visible: true,
                    content: "×",
                    position: { x: 660, y: 15 },
                    size: { width: 25, height: 25 },
                    style: {
                        color: "#999999",
                        fontSize: "28px",
                        fontWeight: "normal",
                        cursor: "pointer",
                        backgroundColor: "transparent",
                        border: "none",
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                    },
                },
                // Welcome heading
                {
                    id: "l_" + uid(),
                    type: "text",
                    name: "Welcome Heading",
                    visible: true,
                    content: "Welcome",
                    position: { x: 390, y: 80 },
                    size: { width: 270, height: 50 },
                    style: {
                        color: "#333333",
                        fontSize: "42px",
                        fontWeight: "bold",
                        fontFamily: "sans-serif",
                        textAlign: "center",
                    },
                },
                // Subheading
                {
                    id: "l_" + uid(),
                    type: "text",
                    name: "Subheading",
                    visible: true,
                    content: "Sign up below for exclusive news & offers.",
                    position: { x: 370, y: 135 },
                    size: { width: 310, height: 45 },
                    style: {
                        color: "#666666",
                        fontSize: "14px",
                        fontFamily: "sans-serif",
                        textAlign: "center",
                        lineHeight: "1.5",
                    },
                },
                // Email input
                {
                    id: "l_" + uid(),
                    type: "email_form",
                    name: "Email Input",
                    visible: true,
                    content: "",
                    position: { x: 380, y: 210 },
                    size: { width: 290, height: 45 },
                    style: {
                        backgroundColor: "#ffffff",
                        border: "1px solid #dddddd",
                        borderRadius: "4px",
                        padding: "12px 16px",
                        fontSize: "14px",
                        fontFamily: "sans-serif",
                        color: "#333333",
                    },
                    metadata: {
                        placeholder: "Enter your Email",
                    },
                },
                // Sign Me Up button
                {
                    id: "l_" + uid(),
                    type: "button",
                    name: "Sign Me Up Button",
                    visible: true,
                    content: "Sign Me Up",
                    position: { x: 380, y: 275 },
                    size: { width: 290, height: 45 },
                    style: {
                        backgroundColor: "#333333",
                        color: "#ffffff",
                        borderRadius: "4px",
                        border: "none",
                        fontSize: "16px",
                        fontWeight: "500",
                        fontFamily: "sans-serif",
                        cursor: "pointer",
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                    },
                },
            ],
        },
        tablet: {
            width: 600,
            height: 450,
            background: "#ffffff",
            borderRadius: 12,
            boxShadow: "0 20px 60px rgba(0, 0, 0, 0.3)",
            layers: [
                {
                    id: "l_" + uid(),
                    type: "shape",
                    name: "Yellow Background",
                    visible: true,
                    content: "",
                    position: { x: 0, y: 0 },
                    size: { width: 300, height: 450 },
                    style: {
                        backgroundColor: "#F5C542",
                        borderRadius: "12px 0 0 12px",
                    },
                },
                {
                    id: "l_" + uid(),
                    type: "image",
                    name: "Car Image",
                    visible: true,
                    content: "/assets/vintage-car.png",
                    position: { x: 50, y: 140 },
                    size: { width: 200, height: 150 },
                    style: {},
                },
                {
                    id: "l_" + uid(),
                    type: "close_button",
                    name: "Close Button",
                    visible: true,
                    content: "×",
                    position: { x: 560, y: 15 },
                    size: { width: 25, height: 25 },
                    style: {
                        color: "#999999",
                        fontSize: "28px",
                        cursor: "pointer",
                        backgroundColor: "transparent",
                        border: "none",
                    },
                },
                {
                    id: "l_" + uid(),
                    type: "text",
                    name: "Welcome Heading",
                    visible: true,
                    content: "Welcome",
                    position: { x: 320, y: 80 },
                    size: { width: 260, height: 50 },
                    style: {
                        color: "#333333",
                        fontSize: "38px",
                        fontWeight: "bold",
                        fontFamily: "sans-serif",
                        textAlign: "center",
                    },
                },
                {
                    id: "l_" + uid(),
                    type: "text",
                    name: "Subheading",
                    visible: true,
                    content: "Sign up below for exclusive news & offers.",
                    position: { x: 310, y: 135 },
                    size: { width: 280, height: 45 },
                    style: {
                        color: "#666666",
                        fontSize: "13px",
                        fontFamily: "sans-serif",
                        textAlign: "center",
                        lineHeight: "1.5",
                    },
                },
                {
                    id: "l_" + uid(),
                    type: "email_form",
                    name: "Email Input",
                    visible: true,
                    content: "",
                    position: { x: 320, y: 200 },
                    size: { width: 260, height: 45 },
                    style: {
                        backgroundColor: "#ffffff",
                        border: "1px solid #dddddd",
                        borderRadius: "4px",
                        padding: "12px 16px",
                        fontSize: "14px",
                        color: "#333333",
                    },
                    metadata: {
                        placeholder: "Enter your Email",
                    },
                },
                {
                    id: "l_" + uid(),
                    type: "button",
                    name: "Sign Me Up Button",
                    visible: true,
                    content: "Sign Me Up",
                    position: { x: 320, y: 260 },
                    size: { width: 260, height: 45 },
                    style: {
                        backgroundColor: "#333333",
                        color: "#ffffff",
                        borderRadius: "4px",
                        border: "none",
                        fontSize: "16px",
                        fontWeight: "500",
                        cursor: "pointer",
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                    },
                },
            ],
        },
        mobile: {
            width: 340,
            height: 500,
            background: "#ffffff",
            borderRadius: 12,
            boxShadow: "0 20px 60px rgba(0, 0, 0, 0.3)",
            layers: [
                {
                    id: "l_" + uid(),
                    type: "shape",
                    name: "Yellow Background",
                    visible: true,
                    content: "",
                    position: { x: 0, y: 0 },
                    size: { width: 340, height: 200 },
                    style: {
                        backgroundColor: "#F5C542",
                        borderRadius: "12px 12px 0 0",
                    },
                },
                {
                    id: "l_" + uid(),
                    type: "image",
                    name: "Car Image",
                    visible: true,
                    content: "/assets/vintage-car.png",
                    position: { x: 70, y: 50 },
                    size: { width: 200, height: 150 },
                    style: {},
                },
                {
                    id: "l_" + uid(),
                    type: "close_button",
                    name: "Close Button",
                    visible: true,
                    content: "×",
                    position: { x: 300, y: 15 },
                    size: { width: 25, height: 25 },
                    style: {
                        color: "#999999",
                        fontSize: "28px",
                        cursor: "pointer",
                        backgroundColor: "transparent",
                        border: "none",
                    },
                },
                {
                    id: "l_" + uid(),
                    type: "text",
                    name: "Welcome Heading",
                    visible: true,
                    content: "Welcome",
                    position: { x: 20, y: 220 },
                    size: { width: 300, height: 40 },
                    style: {
                        color: "#333333",
                        fontSize: "34px",
                        fontWeight: "bold",
                        fontFamily: "sans-serif",
                        textAlign: "center",
                    },
                },
                {
                    id: "l_" + uid(),
                    type: "text",
                    name: "Subheading",
                    visible: true,
                    content: "Sign up below for exclusive news & offers.",
                    position: { x: 20, y: 270 },
                    size: { width: 300, height: 40 },
                    style: {
                        color: "#666666",
                        fontSize: "13px",
                        fontFamily: "sans-serif",
                        textAlign: "center",
                        lineHeight: "1.5",
                    },
                },
                {
                    id: "l_" + uid(),
                    type: "email_form",
                    name: "Email Input",
                    visible: true,
                    content: "",
                    position: { x: 25, y: 335 },
                    size: { width: 290, height: 45 },
                    style: {
                        backgroundColor: "#ffffff",
                        border: "1px solid #dddddd",
                        borderRadius: "4px",
                        padding: "12px 16px",
                        fontSize: "14px",
                        color: "#333333",
                    },
                    metadata: {
                        placeholder: "Email Address",
                    },
                },
                {
                    id: "l_" + uid(),
                    type: "button",
                    name: "Sign Me Up Button",
                    visible: true,
                    content: "Sign Me Up",
                    position: { x: 25, y: 395 },
                    size: { width: 290, height: 45 },
                    style: {
                        backgroundColor: "#333333",
                        color: "#ffffff",
                        borderRadius: "4px",
                        border: "none",
                        fontSize: "16px",
                        fontWeight: "500",
                        cursor: "pointer",
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "center",
                    },
                },
            ],
        },
    },
});

// Template metadata for library
export interface TemplateInfo {
    id: string;
    name: string;
    description: string;
    thumbnail: string;
    category: "email" | "sms" | "general";
    generator: () => Banner;
}

export const templateLibrary: TemplateInfo[] = [
    {
        id: "email-capture",
        name: "Email Capture",
        description: "Simple email signup form with elegant design",
        thumbnail: "/templates/email-capture-thumb.png",
        category: "email",
        generator: emailCaptureTemplate,
    },
    {
        id: "email-sms-capture",
        name: "Email + SMS Capture",
        description: "Capture both email and SMS for maximum engagement",
        thumbnail: "/templates/email-sms-capture-thumb.png",
        category: "sms",
        generator: emailCaptureTemplate, // For now, using same template
    },
];
